export const meta = {
  name: 'v02-kit',
  description: 'Build the Video 02 animation kit: room/projection system, optics primitives, cast extensions, warehouse and robot',
  phases: [
    { title: 'Build', detail: 'four kit builders in the shared source tree, separate files' },
    { title: 'Review', detail: 'independent visual + code review of each kit, then fixes' },
  ],
}

const SRC = '/home/user/Youtube-videos/Future_Got_Weird/Video_02/source'
const COMMON = `
You are building part of the animation kit for an animated explainer (Remotion 4.0.533, React 19, TypeScript) at ${SRC}.
READ FIRST: ${SRC}/../DIRECTION.md (the episode direction), ${SRC}/src/theme.ts, src/lib/motion.ts, src/lib/camera.tsx, src/lib/anim.ts, src/components/Character.tsx, src/components/cast.ts, src/components/Sets.tsx, src/components/Text.tsx, and the official Remotion markup guidance at /root/.claude/skills/remotion-markup/SKILL.md (skim). The provisional room geometry is ${SRC}/src/data/layout.json (metres; schema must be preserved; other code will import it).
Style: Video 01's flat cutout illustration: flat fills, 4 px ink (#162A32) outlines at 1080p, rounded shapes, warm light palette from theme.ts (C.*), no gradients except very subtle shadows, NO textures, NO striped/hatched fills that could shimmer, no glow, no dark fields, no grids (except where explicitly allowed). Everything must be deterministic: pure functions of the frame; use rand() from lib/anim for seeded randomness; never Math.random or Date.
RULES: only create/modify the files assigned to you (listed below); do not edit shared files (lib/*, components/*.tsx at top level, theme.ts, Root.tsx, Main.tsx, data/*). New components go under src/components/v02/ and src/lib/ with the file names given. Export clean, documented, typed components with explicit props. When done, \`cd ${SRC} && npx tsc --noEmit -p .\` must pass for your files (other agents work in parallel in other files; if an error is only in someone else's file, ignore it and say so).
VERIFY VISUALLY: fill in your dev composition file (named below; it is already registered in Root.tsx at 1920x1080, 240 frames). Render stills with: \`cd ${SRC} && COMP=<CompId> SCALE=0.5 node stills.mjs /home/user/Youtube-videos/Future_Got_Weird/Video_02/qa/kit/<CompId> 0 60 120 180 239\` (each run bundles once, ~1-2 min; batch frames into one call). LOOK at the PNGs with the Read tool and fix what looks wrong (overlaps, clipped shapes, wrong layering, off-model faces, lines through things that should block them). Iterate until it looks professional. Do at least two render-inspect-fix rounds.
Return a concise report: files created, exported API (signatures), design decisions, known limitations, and the still paths you inspected.`

const KITS = [
  { key: 'room', comp: 'KitRoom', files: 'src/lib/room.ts, src/components/v02/RoomSet.tsx, src/components/v02/Partition.tsx, src/dev/KitRoom.tsx', prompt: `TASK: the room set and the single projection system that maps plan coordinates (x, z, h in metres from layout.json) to world pixels, with a continuous tilt from the oblique "dollhouse" room view (tilt 0) to the straight-down plan view (tilt 1). Specify it in src/lib/room.ts:
- export types Layout (matching layout.json), PlanPt {x,z,h?}.
- export const LAYOUT (imported from ../data/layout.json).
- export function project(p, tilt, view?) -> {x, y, depth} in 1920x1080 world px. Room view: parallel oblique projection (cabinet-like, no perspective scaling): the relay wall (z=0) at the back/top, the floor receding upward with foreshortening ~0.35, heights drawn at full scale; the room fills the frame comfortably (choose pixels-per-metre so the room width 4.4 m spans ~1500-1600 px and the 2.6 m wall plus floor fits with headroom). Plan view: straight down, wall at the top, uniform scale (same ppm in x and z) so circles stay circles; centre the room. Intermediate tilt interpolates smoothly (floor foreshortening 0.35->1, height scale 1->0, and the plan offset), with an eased helper. Export ppm helpers, depthOrder helpers, and screen-space inverse for the plan view.
- Character placement helper: where to draw a frontal rig standing at (x,z) in room view (feet at the projected floor point; scale chosen so a 1.7 m person is ~1.7 m tall in the projection; the rig is ~440 px tall at scale 1), and a crossfade helper that tells scenes how much of the upright rig vs an overhead token to show for a tilt (rig fades/compresses out between tilt ~0.45-0.75 while the token fades in; no ugly squash).
RoomSet.tsx: <RoomSet tilt={t} ...> draws the back (relay) wall as a plain matte light wall (a light warm tone distinct from the paper background, skirting board, no texture), side walls only if they help, the wood floor with a few plank lines (no stripes that shimmer; few, wide planks), a door and a potted plant for scale placed where they never interfere with light paths (left wall area away from the wall samples), and slot props: children rendered in correct depth order (accept an array of {z, node} items and sort far->near). At tilt 1 it becomes the PlanBoard: paper floor, ink wall line with small 0.5 m tick marks along the relay wall only, the partition as a thick coral line segment, no grid field. Partition.tsx: a coral folding screen (3 panels on small feet, ink outlines, a subtle hinge line) standing along the z axis at layout.occluder (perpendicular to the wall, edge-on to the camera in room view but showing its side face in the oblique projection), with a 'wobble' prop for a comic nudge. The partition must look solid and opaque, taller than a person.
Dev comp KitRoom: frames 0-60 room view with placeholder upright figures (use the real Character rig: checker at layout.operator, guesser at layout.hidden) and a placeholder sensor dot at layout.sensor; 60-150 tilt 0->1; 150-240 plan view with placeholder tokens (simple circles are fine; another agent designs real tokens) and the wall sample points. Draw one straight light path S->W3->H in plan view as a thin line to check alignment (another agent builds the real optics).` },
  { key: 'optics', comp: 'KitOptics', files: 'src/lib/optics.ts, src/components/v02/Optics.tsx, src/dev/KitOptics.tsx', prompt: `TASK: exact optics/geometry primitives in plan space (metres) plus their drawing components. The drawing components take a mapping function toPx(p:{x,z}) -> {x,y} (so they work with any projection; for the dev comp define a simple plan mapping yourself: ppm ~230, wall at top, centred; do NOT import room.ts which another agent is writing).
src/lib/optics.ts (pure TS, no React): segment-segment intersection; segmentBlocked(a,b,layout) against the occluder treated as a rectangle (x +- thickness/2, z0..z1); assertPath(points, layout) that throws an Error naming the blocked segment; pathLength; timeNs(length, c=layout.c_m_per_ns); confocalRadius(tNs, S, W) = (c t - 2|SW|)/2; ellipse param for separated W1/W2 (foci + sum) for completeness; sampleArc(center, r, a0, a1, n); bandMembership(p, center, r, halfWidth); possibleCloud(grid spec, list of {W, r, halfWidth}) returning a scalar field (0..1, product or min of soft band memberships) plus a marching-squares contour extractor that returns smooth closed polygons (Catmull-Rom smoothed) for a threshold, so the "possible locations" region renders as a clean filled blob (no pixel grid, no striation); scatterDirections(normal, n, seed) giving a cosine-weighted fan of directions from a wall point (deterministic). Include a tiny self-check function selfTest() that asserts the provisional layout's numbers (S-H blocked; S-W and W-H clear for W1..W4 at layout.wallSamples; path length 2|SW|+2|WH| etc.) and export it; call it in the dev comp so a violation throws.
src/components/v02/Optics.tsx: <LightPath points toPx t pulses dash intensityFalloff color /> draws a polyline path that 'travels': a bright pulse dot (or short dash train) moves along the path at a given progress t (0..1) with the already-travelled part drawn as a thin line that thins/pales after each bounce (intensity drops per bounce); option to draw the full path statically. <ScatterFan origin dirs length t /> short rays fanning from a wall point (draw-on with t, uneven lengths for cosine weighting). <CandidateArc center r t a0 a1 tone/> an arc drawn on progressively (stroke-dashoffset), clipped to the room's floor area (pass a clip rect). <Band center r halfWidth t /> a translucent ring band. <PossibleCloud field contours t tone /> filled smooth blob(s) with soft edge (use an SVG feGaussianBlur only on this blob with modest radius, deterministic). <WallMarker p label t/>, <SensorGlyph p dir/> (small placeholder; the real sensor prop is drawn by another agent), <ArrivalHistogram bins values peaks t width height labels/> (a clean bar histogram in the house style: rounded bars, ink axis, mono tick labels; supports highlighting a bin range and drawing a time axis in ns), <TimingRuler/> (a ruler from 0 to N ns with "about 30 cm per nanosecond" label option).
Dev comp KitOptics in plan view: draw the room lines (wall, partition) yourself simply; 0-60 a pulse travels S->W3->H->W3->S with a scatter fan at W3; 60-120 four candidate arcs (one per wall sample) draw on, centred on each W with radius |W H| from the layout; 120-200 bands thicken and the possible-location cloud appears around H; 200-240 a histogram panel with a big first-bounce bar and a small late bump. Label everything readable (>= 30 px at 1080p).` },
  { key: 'cast', comp: 'KitCast', files: 'src/components/v02/Cast2.tsx, src/components/v02/Tokens.tsx, src/components/v02/HandheldSensor.tsx, src/dev/KitCast.tsx', prompt: `TASK: extend the accepted Video 01 cast for this episode WITHOUT changing identities (same heads, hair, faces, outfits, colours, line weight as components/Character.tsx and cast.ts). Create src/components/v02/Cast2.tsx: a wrapper/variant of the Character rig (copy the needed drawing code into your file if you must; do not edit Character.tsx) that adds: (1) legs that can move: per-leg hip angle and knee bend (simple two-segment legs with the same pants/shoe style) so a character can WALK sideways across the floor with a believable frontal/3-4 cutout walk cycle (export walkPose(phase) helper and a stride length so feet do not slide: provide a function that converts distance travelled into cycle phase), plus a TIPTOE variant (sneaking), a CROUCH (knees bent, body lowered ~25%), and a SETTLE (weight shift); (2) a 'peek' head lean option and hand-over-mouth / hands-on-hips / arms-crossed pose presets (as Pose objects using the existing Arm convention); (3) 'smug' expression preset (half-lidded eyes: add an eyelid option) and 'busted' (wide eyes, small 'o' mouth) for the guesser; 'deadpan' for the checker. Keep the existing props API compatible (pose, look, frame, x, y, scale, flip, holdL/holdR, front/pass, life).
Tokens.tsx: overhead (top-down) tokens for the plan view: <GuesserToken/> and <CheckerToken/> = a top-down head (hair seen from above: guesser's red spiky crown, checker's grey bob with the pencil and glasses rims peeking at the front edge), shoulders in shirt/cardigan colours, a soft floor shadow; ~0.5 m wide in plan (accept a px size). A facing direction prop rotates them. They must read as the same people as the frontal rigs.
HandheldSensor.tsx: a small boxy time-of-flight sensor module with a short grip, drawn to be held in a rig hand via holdR/holdL (hand at 0,0): the far face (toward the wall, away from camera) is implied; the side facing us shows a tiny readout screen (render a mini histogram with a tall first bar and a small late bump; the screen content is a prop so scenes can animate it) and a small status LED; teal body with ink outline, coral accent, NOT a phone and not branded. Also a plan-view glyph <SensorTop/> (seen from above, with an emitter notch showing its facing direction).
Dev comp KitCast: the guesser tiptoes from x=300 to x=1200 (feet must not slide: compute phase from distance), settles into a smug hands-on-hips pose behind where a partition would be (draw a simple coral rectangle as a stand-in), then a busted reaction; the checker stands at left holding the HandheldSensor at chest height with the readout facing camera, deadpan; then show both tokens in plan at the end. Check hands actually hold the sensor grip (use reach/handWorld).` },
  { key: 'warehouse', comp: 'KitWarehouse', files: 'src/components/v02/Warehouse.tsx, src/components/v02/DeliveryBot.tsx, src/dev/KitWarehouse.tsx', prompt: `TASK: the act-5 illustrative application: a simple warehouse/aisle environment with a BLIND CORNER, and an original small delivery robot. Warehouse.tsx: <WarehouseSet view='front'|'plan' tilt .../> using its own small projection in the same spirit as the room (oblique front view, plus a plan view with a smooth tilt between them; implement locally in your file, do not import src/lib/room.ts which another agent is writing): two shelving runs that meet at an L corner so a robot travelling along one aisle cannot see a person/cart coming down the other; a plain light wall section across the junction that can act as the relay surface (matte, flat); floor lane markings (a few, wide, no stripes that shimmer); boxes on shelves in the house palette (flat, few colours, no texture). Export the corner geometry in metres (plan) so optics can be drawn later. DeliveryBot.tsx: an original small wheeled delivery robot (squat rounded box body ~0.6 m tall, cargo lid, two wheels with spokes that rotate with distance travelled, a small sensor head on a short mast with an emitter window, two simple dot 'eyes' on a front panel for readable reactions: neutral, cautious (squint), pleased) in teal/saffron/coral house colours with ink outlines. It must NOT look like the channel's mascot (a teal speech-bubble robot face with a bent antenna and coral disk); avoid a speech-bubble head and avoid an antenna with a disk. Props: x, y, scale, travelled (m) -> wheel rotation, brake (body pitch forward on braking), eyes state, sensor pulse t. Also a plan-view glyph <BotTop/>. Dev comp KitWarehouse: front view, the robot rolls toward the corner and brakes with anticipation and a little pitch-and-settle; then tilt to plan view showing the corner geometry and the bot glyph; a person token placeholder approaching on the other aisle.` },
]

phase('Build')
const built = await parallel(KITS.map(k => () =>
  agent(COMMON + `\n\nYOUR FILES: ${k.files}\nYOUR DEV COMPOSITION: ${k.comp}\n\n` + k.prompt, { label: `kit:${k.key}`, phase: 'Build' })
    .then(r => ({ key: k.key, comp: k.comp, files: k.files, report: r }))))

phase('Review')
const reviewed = await parallel(built.filter(Boolean).map(b => () =>
  agent(COMMON + `\n\nYOUR FILES (to review and fix): ${b.files}\nDEV COMPOSITION: ${b.comp}\n\nTASK: you are an independent reviewer of a kit another agent just built. Its report:\n${b.report}\n\nRender stills of ${b.comp} at frames 0, 40, 80, 120, 160, 200, 239 (one stills.mjs call) and read every PNG. Also read the code. Find defects: off-model characters (compare against Video 01 rigs in components/Character.tsx and the reference frames in /home/user/Youtube-videos/Future_Got_Weird/Video_02/art/v01_refs/), hands not touching what they hold, sliding feet, wrong layering/depth order, lines crossing opaque objects, clipped or tiny text (< 30 px at 1080p), textures or stripes that would shimmer, non-deterministic code, APIs that will be awkward for scene builders (missing props for timing, magic numbers). FIX the defects in those files directly (same file-ownership rules), re-render, and verify. Return: defects found, fixes made, remaining limitations, final API summary.`, { label: `review:${b.key}`, phase: 'Review' })
    .then(r => ({ key: b.key, review: r }))))

return { built: built.filter(Boolean).map(b => ({ key: b.key, report: b.report })), reviewed }
